# Julia Control Flow

## Assertions
The `@assert` operator can be used to check if a condition is met, and stop program execution if it isn't

In [1]:
a = 5
b = 5
@assert a==b

In [2]:
a = 5
c = 6
@assert a==c

LoadError: AssertionError: a == c

## Loops

All loops follow the same syntax
```
*while/for* *conditional statement*
    *the action within the loop
    on new indented lines*
*end*
```

### While loops

`while` loops run until their condition is not met

In [6]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5


### For loops
`for` loops run through an collection, and perform some action on each element 

In [7]:
for i in 1:5
    println(i)
end

1
2
3
4
5


The `in` keyword at the start of the loop can also be replaced with a `=`

In [1]:
for i = 1:5
    println(i)
end

1
2
3
4
5


We can nest for loops in the usual way, for example if we want to fill a pre-defined 2D matrix with the sum of its index values

In [6]:
m = 4
n = 5
addition_table = zeros(m,n)
for i in 1:m
    for j in 1:n
        addition_table[i,j] = i+j
    end
end
addition_table

4×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0
 5.0  6.0  7.0  8.0  9.0

We can also write this more compactly by specifying both loops on one line

In [14]:
addition_table = zeros(m,n)
for i in 1:m, j in 1:n
    addition_table[i,j] = i+j
end
addition_table

  0.000022 seconds (29 allocations: 928 bytes)


4×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0
 5.0  6.0  7.0  8.0  9.0

We can also create the array in-place, removing the need to create a blank array before running the loop

In [11]:
addition_table = [i+j for i in 1:m, j in 1:n]
addition_table

4×5 Matrix{Int64}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

## Conditionals
Conditionals allow us to execute different actions depending on the state of other parts of our program. They are normally stated in a similar manner to Python

### Standard Notation

In [23]:
a = 2
b = 4
if a > b
    println(a)
elseif a < b
    println(b)
end

4


They can also be put on one line (but this is inadvisable unless the statement is very short)

In [24]:
if a > b println(a) elseif a < b println(b) end

4


### Ternary Operators

The same logic can be stated using ternary operators, where the condition is stated on one side of the `?` symbol, and the return values are stated on the other side. The return for the condition being true comes first, then a `:` symbol, then the return for the condition being false. You can think of the `?` as meaning "is this true?" and the `:` meaning "if not, then do this" 

In [25]:
(a > b) ? a : b

4

### Short-Circuit Evaluation
Conditionals can also be stated using short-circuit evaluation, which allow the evaluation to finish early (i.e. short circuit) if one of the conditions is true or false, rather than evaluation all of the conditions before returning a value. To short-circuit when any of the conditions are false, use the `&&` operator, which returns `true` only if the conditions on either side of it are true

In [40]:
false && (2>1)

false

To short circuit when any of the conditions are true, use the `||` operator, which returns 'true' if either or both of the conditions on either side of it are true

In [41]:
true || (2<1)

true

The conditions are evaluated from left to right. We can see that the condition on the right-hand side is not even considered by inserting a print statement before the condition on the right. In both cases, nothing is printed because the short-circuit kicks in on the lefthand side

In [42]:
false && (println("2 is larger than 1") ; 2>1)

false

In [43]:
true || (println("2 is larger than 1") ; 2>1)

true

In contrast, in the example below the lefthand condition is false, so evaluation has to move to the righthand side

In [44]:
false || (println("2 is larger than 1") ; 2>1)

2 is larger than 1


true

Because the righthand side of the `&&` operator does not get evaluated if the lefthand side is false, it does not have to be a conditional. We can even make it report an error depending on the condition of the lefthand side

In [47]:
x = 10

(x>1) && error("x cannot be larger than 1")

LoadError: x cannot be larger than 1